[updates]
auto_update = true
# Update every 7 days
auto_update_interval_hours = 168
[display]

[directories]
custom_pages_dir = "/Users/adrien/.local/share/tealdeer/pages"

[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = "blue"
underline = false
bold = true
italic = false

[style.example_text]
foreground = "green"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "cyan"
underline = true
bold = false
italic = false

